name: flutter_onnx_inference_crash
description: "A new Flutter project."

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  onnxruntime:
    git:
      url: https://github.com/ente-io/onnxruntime.git
      ref: ente_onnxruntime

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
